# Generated by Django 3.2.20 on 2023-07-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SongPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_order', models.IntegerField()),
                ('part_name', models.CharField(max_length=50)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongPartAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_order', models.IntegerField()),
                ('action_object', models.CharField(choices=[('AMF', 'Arturia Micro Freak'), ('EMS', 'Elektron Model:Samples'), ('ACU', 'Acustic Guitar'), ('EG', 'Electric Guitar'), ('ZG3', 'Zoom G3')], max_length=8)),
                ('action_name', models.CharField(choices=[('NONE', 'No action')], max_length=8)),
                ('action_param', models.CharField(max_length=50)),
                ('song_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.songpart')),
            ],
        ),
    ]
